name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'movieticket-booking'
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        package: ./build
